In [214]:
import pandas as pd
import numpy as np
import eikon as ek
ek.set_app_key('b4229eae2c644ec8a0aab0bb0fb83b13a38eb2c7')
import plotly.express as px
import plotly.graph_objects as go
from IPython.display import HTML
from chart_studio.plotly import plot, iplot
import datetime
from datetime import date
import emoji

In [310]:
def lp_setup():
    picks = ['LUV', 'UBER.K', 'NVDA.O', 'MCD', 'FB.O', 'RF', 'TJX', 'Z.O', 'NVS', 'GILD.O','SYK', 'AEG', 'LMT', 'TOT', 'AMZN.O', 'GOOGL.O', 'BE', 'NVDA.O',
             'ADI.O', 'PLUG.O', 'MXIM.O', 'DAL', 'LUV', 'CRWD.O', 'SGEN.O', 'NOW', 'TXT', 'BORR.K', 'FB.O', 'QCOM.O', 'NVDA.O', 'PYPL.O', 'CSCO.O', 'WIX.O', 'APTV.K', 'LUV',
             'LUV', 'TMO', 'PING.K', 'PAA', 'AZN.P', 'GILD.O', 'WYNN.O', 'QCOM.O', 'ZM.O', 'AAPL.O', 'NFLX.O', 'BA', 'BLMN.O', 'FEYE.O', 'KSU', 'JPM', 'MSFT.O', 'WYNN.O', 'FB.O',
             'GOOGL.O', 'AMZN.O', 'AAPL.O', 'BX', 'FB.O', 'HD', 'MSFT.O', 'NFLX.O', 'NKE', 'UNH', 'CHWY.K', 'AMD.O', 'PYPL.O', 'MELI.O', 'SPLK.O', 'CRSP.O', 'TWLO.K', 'BL.O',
             'SWKS.O', 'NTLA.O', 'MSFT.O', 'AMZN.O', 'TSLA.O', 'AAPL.O', 'XOM', 'JNJ', 'AXP', 'CLX', 'BRKb', 'CVS', 'AMZN.O', 'MSFT.O', 'TSLA.O', 'AMD.O', 'BA', 'LUV', 'CCL',
             'MGM', 'LYV', 'DKNG.O', 'MSFT.O', 'AMZN.O', 'NFLX.O', 'PYPL.O', 'UNH', 'HD', 'DIS', 'CLX', 'INO.O', 'NVDA.O', 'ZBRA.O', 'FLIR.O', 'ECL', 'C', 'BAC', 'LUV', 'SNY.O',
             'AMD.O', 'NTDOY.PK', 'SNE', 'MSFT.O', 'F', '0593q.L', 'PEP.O', 'NSRGY.PK', 'PG', 'RHHBY.PK', 'PFE', 'MAR.O', 'MGM', 'CHK', 'CVX', 'BA', 'LUV', 'ROKU.O', 'M', 'PYPL.O', 'AMC',
             'ABBV.N', 'ASML.O', 'CGNX.O', 'EA.O', 'EOG.N', 'GILD.O', 'HUM.N', 'JD.O', 'MDB.O', 'ROP.N', 'MSFT.O', 'AMZN.O', 'DIS', 'ZM.O', 'NVDA.O', 'VZ', 'LUV', 'VRTX.O',
             'TTD.O', 'GMED.K', 'APPN.O', 'NOW', 'MTCH.O', 'RUBI.K', 'PENN.O', 'SPLK.O', 'NVDA.O', 'LVGO.O',  'MSFT.O', 'AAPL.O', 'AMZN.O', 'T', 'JPM', 'UNH', 'ATVI.O', 'V', 'LUV',
             'TSLA.O', 'CVX', 'TGT', 'ALGN.O', 'MAR.O', 'AMZN.O', 'AMZN.O', 'EXPE.O', 'LUV', 'TJX', 'V', 'IPG', 'CCL', 'MITT.K', 'MRNA.O', 'DVAX.O',
             'AMZN.O', 'AVGO.O', 'PYPL.O', 'ILMN.O', 'EQIX.O', 'AAPL.O', 'TSM', 'ATVI.O', 'TSLA.O', 'DHR', 'AAPL.O', 'ABBV.N', 'AMZN.O', 'AXP', 'CHWY.K', 'FIVN.O','MRK', 'OKTA.O',
             'TDOC.K', 'VRSN.O', 'LUV', 'NCLH.K', 'AMZN.O', 'MGM', 'EQIX.O', 'F', 'THRM.O', 'BA', 'LVS', 'DIS', 'MDT', 'MRK', 'MAR.O', 'PENN.O', 'DDOG.O', 'AMZN.O', 'TWLO.K', 'NVCR.O', 'ZS.O',
             'TTD.O', 'SHOP.K','TEAM.O', 'MELI.O', 'NVDA.O', 'AMZN.O', 'PYPL.O', 'VLO', 'GOOG.O', 'AAPL.O', 'JPM', 'NFLX.O', 'DLR', 'MSFT.O', 'NVDA.O', 'AMZN.O', 'PYPL.O', 'VLO', 'GOOG.O',
             'AAPL.O', 'JPM', 'NFLX.O', 'DLR', 'MSFT.O','LVGO.O', 'NVDA.O', 'AAPL.O', 'AMZN.O', 'COST.O', 'ZM.O', 'SHOP.K', 'NK.O', 'DPZ', 'W', 'AMZN.O', 'NFLX.O', 'MSFT.O', 'NVDA.O', 'JNJ', 'DIS',
             'LUV', 'TTD.O', 'PANW.K', 'BABA.K']
    
    
    
    
    
    stocks = []
    for p in picks:
        if p not in stocks:
            stocks.append(p)
        
    start = ek.get_data(stocks, fields='TR.PriceClose', parameters={'SDate': '2020-05-29'})[0]
    start = start.rename(columns = {'Instrument': 'Stocks'})
    start = start.set_index('Stocks')



    
    return start.to_pickle('start.pkl')

In [311]:
lp_setup()

In [314]:
def league():
    ken = pd.DataFrame({'Stocks': ['LUV', 'UBER.K', 'NVDA.O', 'MCD', 'FB.O', 'RF', 'TJX', 'Z.O', 'NVS', 'GILD.O'], 'Investment': [10000, 20000, 5000, 5000, 10000, 15000, 5000, 10000,10000, 10000], 'id': 'Ken'})
    ann_mar = pd.DataFrame({'Stocks': ['SYK', 'AEG', 'LMT', 'TOT', 'AMZN.O', 'GOOGL.O'], 'Investment': [10000,25000,20000,25000,10000,10000], 'id': 'Ann Marie'})
    hoser = pd.DataFrame({'Stocks': ['BE', 'NVDA.O','ADI.O', 'PLUG.O', 'MXIM.O', 'DAL', 'LUV', 'CRWD.O', 'SGEN.O', 'NOW'], 'Investment': [8750,8750,8750,8750,8750,15000,15000,8750,8750,8750], 'id': 'Hosegood'})
    jack = pd.DataFrame({'Stocks': [ 'TXT', 'BORR.K', 'FB.O', 'QCOM.O', 'NVDA.O', 'PYPL.O', 'CSCO.O', 'WIX.O', 'APTV.K', 'LUV'], 'Investment': [5000,5000,15000,10000,15000,10000,10000,15000,5000,10000], 'id': 'Jack'})
    christi = pd.DataFrame({'Stocks': [ 'LUV', 'TMO', 'PING.K', 'PAA', 'AZN.P', 'GILD.O', 'WYNN.O', 'QCOM.O', 'ZM.O'], 'Investment': [10000, 17000, 8500, 9750, 14750, 13000, 10000, 8000, 9000], 'id': 'Jeff Christi'})
    flam = pd.DataFrame({'Stocks': ['AAPL.O', 'NFLX.O', 'BA', 'BLMN.O', 'FEYE.O', 'KSU', 'JPM', 'MSFT.O', 'WYNN.O', 'FB.O',], 'Investment': [20000,5000,5000,5000,20000,10000,10000,10000,10000,5000], 'id': 'Louis'})
    ak = pd.DataFrame({'Stocks': ['GOOGL.O', 'AMZN.O', 'AAPL.O', 'BX', 'FB.O', 'HD', 'MSFT.O', 'NFLX.O', 'NKE', 'UNH'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id': 'Anthony'})
    sd = pd.DataFrame({'Stocks': ['CHWY.K', 'AMD.O', 'PYPL.O', 'MELI.O', 'SPLK.O', 'CRSP.O', 'TWLO.K', 'BL.O','SWKS.O', 'NTLA.O',], 'Investment': [8000, 12000, 10000, 8000, 12000, 8000, 10000, 10000, 10000, 12000], 'id':'Sergio'})
    db = pd.DataFrame({'Stocks': ['MSFT.O', 'AMZN.O', 'TSLA.O', 'AAPL.O', 'XOM', 'JNJ', 'AXP', 'CLX', 'BRKb', 'CVS'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Debbie'})
    mk = pd.DataFrame({'Stocks': ['AMZN.O', 'MSFT.O', 'TSLA.O', 'AMD.O', 'BA', 'LUV', 'CCL','MGM', 'LYV', 'DKNG.O',], 'Investment': [9769, 7330, 12525, 10444, 10210, 10433, 10215, 10291, 8849, 9925], 'id': 'Mike'})
    ab = pd.DataFrame({'Stocks': ['MSFT.O', 'AMZN.O', 'NFLX.O', 'PYPL.O', 'UNH', 'HD', 'DIS', 'CLX', 'INO.O', 'NVDA.O'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Ali'})
    jw = pd.DataFrame({'Stocks': ['ZBRA.O', 'FLIR.O', 'ECL', 'C', 'BAC', 'LUV', 'SNY.O'], 'Investment': [17500, 17500, 17500, 10000, 10000, 17500, 10000], 'id': 'Westy'})
    jpl = pd.DataFrame({'Stocks': ['AMD.O', 'NTDOY.PK', 'SNE', 'MSFT.O', 'F', '0593q.L', 'PEP.O', 'NSRGY.PK', 'PG', 'RHHBY.PK', 'PFE'] ,'Investment': [5000, 5000, 5000, 5000, 5000, 5000, 10000, 15000, 15000, 15000, 15000], 'id': 'JPL'})
    aw = pd.DataFrame({'Stocks': ['MAR.O', 'MGM', 'CHK', 'CVX', 'BA', 'LUV', 'ROKU.O', 'M', 'PYPL.O', 'AMC'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Alyssa'})
    pr = pd.DataFrame({'Stocks': [ 'ABBV.N', 'ASML.O', 'CGNX.O', 'EA.O', 'EOG.N', 'GILD.O', 'HUM.N', 'JD.O', 'MDB.O', 'ROP.N'], 'Investment': [15000,18000,3000,5000,4000,14000,10000,11000,15000,5000], 'id':'Paul R'})
    fr = pd.DataFrame({'Stocks': ['AAPL.O', 'ABBV.N', 'AMZN.O', 'AXP', 'CHWY.K', 'FIVN.O','MRK', 'OKTA.O','TDOC.K', 'VRSN.O'], 'Investment': [17000,8000,21000,6000,10000,10000,6000,11000,8000,3000], 'id':'Farrah'})
    el = pd.DataFrame({'Stocks': [ 'MSFT.O', 'AMZN.O', 'DIS', 'ZM.O', 'NVDA.O', 'VZ', 'LUV', 'VRTX.O'], 'Investment': [20000, 15000, 10000, 10000, 10000, 15000, 10000, 10000], 'id':'Evan'})
    jb = pd.DataFrame({'Stocks': [ 'TTD.O', 'GMED.K', 'APPN.O', 'NOW', 'MTCH.O', 'RUBI.K', 'PENN.O', 'SPLK.O', 'NVDA.O', 'LVGO.O'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'JB'})
    ds = pd.DataFrame({'Stocks': [ 'MSFT.O', 'AAPL.O', 'AMZN.O', 'T', 'JPM', 'UNH', 'ATVI.O', 'V', 'LUV'], 'Investment': [14843.25, 14943.18, 14654.22, 15183.12, 9925.62, 9755.20, 10581.06, 4881, 5232.30], 'id':'Daniel'})
    eh = pd.DataFrame({'Stocks': [ 'TSLA.O', 'CVX', 'TGT', 'ALGN.O', 'MAR.O', 'AMZN.O'], 'Investment': [17535, 5502, 7339.8, 14737.2, 5310, 48847.4], 'id':'Emily'})
    jt = pd.DataFrame({'Stocks': [ 'AMZN.O', 'EXPE.O', 'LUV', 'TJX', 'V', 'IPG', 'CCL', 'MITT.K', 'MRNA.O', 'DVAX.O'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Jon T'})
    ar = pd.DataFrame({'Stocks': [ 'AMZN.O', 'AVGO.O', 'PYPL.O', 'ILMN.O', 'EQIX.O', 'AAPL.O', 'TSM', 'ATVI.O', 'TSLA.O', 'DHR'], 'Investment': [10500, 10500, 10500, 10500, 10500, 10500, 10500, 10500, 5500, 10500], 'id':'Anish'})
    mb = pd.DataFrame({'Stocks': ['ASML.O', 'MSFT.O'], 'Investment': [9990, 10], 'id':'Burke'})
    nd = pd.DataFrame({'Stocks': ['LUV', 'NCLH.K', 'AMZN.O', 'MGM', 'EQIX.O'], 'Investment': [20000, 20000, 20000, 20000, 20000], 'id':'Dado'})
    gk = pd.DataFrame({'Stocks': ['F', 'THRM.O', 'BA', 'LVS', 'DIS', 'MDT', 'MRK', 'MAR.O'], 'Investment': [12500, 12500, 12500, 12500, 12500, 12500, 12500, 125000], 'id':'Greg'})
    cp = pd.DataFrame({'Stocks': ['PENN.O', 'DDOG.O', 'AMZN.O', 'TWLO.K', 'NVCR.O', 'ZS.O', 'TTD.O', 'SHOP.K','TEAM.O', 'MELI.O'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Jon T'})
    ph = pd.DataFrame({'Stocks': ['NVDA.O', 'AMZN.O', 'PYPL.O', 'VLO', 'GOOG.O', 'AAPL.O', 'JPM', 'NFLX.O', 'DLR', 'MSFT.O'], 'Investment': [15000, 15000, 15000, 10000, 10000, 10000, 10000, 5000, 5000, 5000], 'id':'Paul H'})
    hh = pd.DataFrame({'Stocks': ['AMZN.O', 'NFLX.O', 'MSFT.O', 'NVDA.O', 'JNJ', 'DIS', 'LUV', 'TTD.O', 'PANW.K', 'BABA.K'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Jon T'})
    sb = pd.DataFrame({'Stocks': ['LVGO.O', 'NVDA.O', 'AAPL.O', 'AMZN.O', 'COST.O', 'ZM.O', 'SHOP.K', 'NK.O', 'DPZ', 'W'], 'Investment': [5000, 10000, 15000, 15000, 12500, 5000, 7500, 5000, 12500, 12500], 'id':'Scott B'})
    
    players = [ken, ann_mar, hoser, jack, christi, flam, ak, sd, db, mk, ab, jw, jpl, aw, pr, fr, el, jb, ds, eh, jt, ar, mb, nd, gk, cp, ph, hh, sb]
    master = pd.concat(players)
    master = master.set_index('Stocks')
    start = pd.read_pickle('start.pkl')
    
    today = datetime.date.today()
    offset = max(1, (today.weekday() + 6) % 7 - 3)
    timedelta = datetime.timedelta(offset)
    most_recent = today - timedelta
    last_date = most_recent.strftime('%Y-%m-%d')

    fields = [ek.TR_Field('DSPLY_NAME'), ek.TR_Field('TR.GICSSector'), ek.TR_Field('TR.PriceClose', params={'SDate': last_date}), ek.TR_Field('TR.TotalReturn', params={'SDate': '2020-05-29','EDate': last_date})]
    today = ek.get_data(stocks, fields=fields)[0]
    today = today.rename(columns = {'Instrument': 'Stocks'})
    today = today.set_index('Stocks')

    master = master.join(start)
    master['Shares'] = master['Investment'] / master['Price Close']
    master = master.rename(columns = {'Price Close': 'Cost per Share'})
    master = master.join(today)
    master['Todays Value'] = master['Shares'] * master['Price Close']
    roster = master['id'].drop_duplicates().to_list()


    bms = []
    for r in roster:
        p = master[master['id']==r]
        x = p.index.to_list()
        t = np.array(p['Shares'])
        s = ek.get_timeseries(x, start_date='2019-12-31', end_date='2020-05-29', interval='daily', fields='CLOSE')
        s['Strat'] = np.dot(t, s.T)
        w = s.pct_change().dropna()
        l = bm_rets.join(w['Strat'])
        lv = l.corr()
        bm = lv['Strat'][0:-1].idxmax()
        r_2 = round(lv['Strat'][0:-1].max()**2, 4)*100
        q = (r , bm, r_2)
        bms.append(q)
    

    benchmarks = pd.DataFrame(bms)
    benchmarks = benchmarks.rename(columns = {0:'id', 1:'Benchmark', 2:'R Squared'})
    benchmarks = benchmarks.set_index('id')
    master = master.reset_index()
    master = master.set_index('id')
    master = master.join(benchmarks)
    master['Total Dividends'] = ((1+(master['Total Return'].astype(float)/100)) * master['Investment'].astype(float)) - master['Todays Value'].astype(float)
    master = master.reset_index()
    league = master.groupby('id').sum()
    league = league.filter(['Investment', 'Todays Value', 'Total Dividends'])
    league['Total Return'] = ((league['Todays Value'] + league['Total Dividends'])/league['Investment'])-1
    tr_tab = league['Total Return'].quantile([0.25, 0.5, 0.75])
    trs = league['Total Return'].to_list()

    quants = []
    for t in trs:
        if t > tr_tab.iloc[2]:
            x = emoji.emojize(':heavy_dollar_sign::heavy_dollar_sign::heavy_dollar_sign::heavy_dollar_sign:')
        elif t <= tr_tab.iloc[2] and t > tr_tab.iloc[1]:
            x = emoji.emojize(':heavy_dollar_sign::heavy_dollar_sign::heavy_dollar_sign:')
        elif t <= tr_tab.iloc[1] and t > tr_tab.iloc[0]:
             x = emoji.emojize(':heavy_dollar_sign::heavy_dollar_sign:')
        else:
            x = emoji.emojize(':poop::poop::poop::poop:', use_aliases=True)
        quants.append(x)
    
    league['Rank'] = quants
    
    league = league.sort_values(by = 'Total Return', ascending = False)
    master = master.set_index('id')
    league_fin = league.join(master['Benchmark'])
    league_fin = league_fin.drop_duplicates()
    league_fin = league_fin.sort_values('Total Return', ascending=False)
    bms = ['IWF', 'IWB', 'IWD', 'IWR', 'IWP', 'IWS', 'IWM', 'IWO', 'IWN', 'QQQ.O', 'IVV']
    fields = [ek.TR_Field('TR.FundName'), ek.TR_Field('TR.TotalReturn', params={'SDate': '2020-05-29','EDate': last_date})]
    bms = ek.get_data(bms, fields=fields)[0]
    bmarks = bms.rename(columns = {'Instrument':'Benchmark', 'Fund Name': 'Benchmark Name', 'Total Return': 'Benchmark Total Return'}).set_index('Benchmark')
    bmarks['Benchmark Total Return'] = bmarks['Benchmark Total Return']/100
    b_marks = league_fin['Benchmark'].to_list()

    bmtr = []
    bmname = []
    for b in b_marks:
        x = bmarks['Benchmark Total Return'].loc[b]
        y = bmarks['Benchmark Name'].loc[b]
        bmtr.append(x)
        bmname.append(y)
    
    league_fin['Benchmark Name'] = bmname
    league_fin['Beanchmark Total Return'] = bmtr
    league_fin['Outperformance'] = league_fin['Total Return'] - league_fin['Beanchmark Total Return']
    league_fin['Outperforming Benchmark'] =[emoji.emojize(':heavy_check_mark:', use_aliases=True) if x > 0 else emoji.emojize(':x:', use_aliases=True) for x in league_fin['Outperformance']]
    league_final = league_fin.drop(['Benchmark', 'Outperformance'], axis = 1)
    master.to_pickle('master.pkl')

    
    
    
    return  league_final

In [315]:
x = league()
x

C:\Users\f16se\Miniconda3\lib\site-packages\eikon\data_grid.py:244: FutureWarning:

The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

C:\Users\f16se\Miniconda3\lib\site-packages\eikon\time_series.py:282: FutureWarning:

The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

C:\Users\f16se\Miniconda3\lib\site-packages\eikon\time_series.py:284: FutureWarning:

The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

C:\Users\f16se\Miniconda3\lib\site-packages\eikon\time_series.py:286: FutureWarning:

The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

C:\Users\f16se\Miniconda3\lib\site-packages\eikon\time_series.py:208: FutureWarning:

The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

,Investment,Todays Value,Total Dividends,Total Return,Rank,Benchmark Name,Beanchmark Total Return,Outperforming Benchmark
id,,,,,,,,
Ali,100000.00,100000.00,0.0,0.000000e+00,💲💲,Invesco QQQ Trust Series 1,0.091869,❌
Debbie,100000.00,100000.00,0.0,0.000000e+00,💲💲,iShares Core S&P 500 ETF,-0.051702,✔
Mike,99991.00,99991.00,0.0,0.000000e+00,💲💲,iShares Russell 2000 Growth ETF,-0.064137,✔
Ken,100000.00,100000.00,0.0,0.000000e+00,💲💲,iShares Russell 2000 Growth ETF,-0.064137,✔
Jeff Christi,100000.00,100000.00,0.0,0.000000e+00,💲💲,iShares Russell 1000 ETF,-0.052719,✔
Hosegood,100000.00,100000.00,0.0,0.000000e+00,💲💲,iShares Russell Mid-Cap Growth ETF,0.008829,❌
Alyssa,100000.00,100000.00,0.0,0.000000e+00,💲💲,iShares Russell 2000 Value ETF,-0.252557,✔
Westy,100000.00,100000.00,0.0,0.000000e+00,💲💲,iShares Russell 1000 Value ETF,-0.154581,✔
Daniel,99998.95,99998.95,0.0,0.000000e+00,💲💲,iShares Russell 1000 Growth ETF,0.044072,❌
Burke,10000.00,10000.00,0.0,0.000000e+00,💲💲,iShares Russell Mid-Cap Growth ETF,0.008829,❌
Anthony,100000.00,100000.00,0.0,0.000000e+00,💲💲,iShares Russell 1000 Growth ETF,0.044072,❌
Ann Marie,100000.00,100000.00,0.0,0.000000e+00,💲💲,iShares Russell Mid-Cap ETF,-0.106638,✔
Emily,99271.40,99271.40,0.0,-1.110223e-16,💩💩💩💩,Invesco QQQ Trust Series 1,0.091869,❌
Dado,100000.00,80000.00,0.0,-2.000000e-01,💩💩💩💩,iShares Russell Mid-Cap Value ETF,-0.185394,❌
Jon T,300000.00,230000.00,0.0,-2.333333e-01,💩💩💩💩,iShares Russell Mid-Cap Growth ETF,0.008829,❌
Greg,212500.00,162500.00,0.0,-2.352941e-01,💩💩💩💩,iShares Russell 2000 ETF,-0.155633,❌
Paul H,100000.00,75000.00,0.0,-2.500000e-01,💩💩💩💩,iShares Russell 1000 Growth ETF,0.044072,❌
Farrah,100000.00,62000.00,0.0,-3.800000e-01,💩💩💩💩,Invesco QQQ Trust Series 1,0.091869,❌
Scott B,100000.00,50000.00,0.0,-5.000000e-01,💩💩💩💩,Invesco QQQ Trust Series 1,0.091869,❌

In [ ]:
df