In [1]:
import pandas as pd
import numpy as np
import eikon as ek
ek.set_app_key('b4229eae2c644ec8a0aab0bb0fb83b13a38eb2c7')
import plotly.express as px
import plotly.graph_objects as go
from IPython.display import HTML
from chart_studio.plotly import plot, iplot
import datetime
from datetime import date
import emoji
import plotly.io as pio
from plotly.subplots import make_subplots

In [2]:
def lp_setup():
    picks = ['LUV', 'UBER.K', 'NVDA.O', 'MCD', 'FB.O', 'RF', 'TJX', 'Z.O', 'NVS', 'GILD.O','SYK', 'AEG', 'LMT', 'TOT', 'AMZN.O', 'GOOGL.O', 'BE', 'NVDA.O',
             'ADI.O', 'PLUG.O', 'MXIM.O', 'DAL', 'LUV', 'CRWD.O', 'SGEN.O', 'NOW', 'TXT', 'BORR.K', 'FB.O', 'QCOM.O', 'NVDA.O', 'PYPL.O', 'CSCO.O', 'WIX.O', 'APTV.K', 'LUV',
             'LUV', 'TMO', 'PING.K', 'PAA', 'AZN.P', 'GILD.O', 'WYNN.O', 'QCOM.O', 'ZM.O', 'AAPL.O', 'NFLX.O', 'BA', 'BLMN.O', 'FEYE.O', 'KSU', 'JPM', 'MSFT.O', 'WYNN.O', 'FB.O',
             'GOOGL.O', 'AMZN.O', 'AAPL.O', 'BX', 'FB.O', 'HD', 'MSFT.O', 'NFLX.O', 'NKE', 'UNH', 'CHWY.K', 'AMD.O', 'PYPL.O', 'MELI.O', 'SPLK.O', 'CRSP.O', 'TWLO.K', 'BL.O',
             'SWKS.O', 'NTLA.O', 'MSFT.O', 'AMZN.O', 'TSLA.O', 'AAPL.O', 'XOM', 'JNJ', 'AXP', 'CLX', 'BRKb', 'CVS', 'AMZN.O', 'MSFT.O', 'TSLA.O', 'AMD.O', 'BA', 'LUV', 'CCL',
             'MGM', 'LYV', 'DKNG.O', 'MSFT.O', 'AMZN.O', 'NFLX.O', 'PYPL.O', 'UNH', 'HD', 'DIS', 'CLX', 'INO.O', 'NVDA.O', 'ZBRA.O', 'FLIR.O', 'ECL', 'C', 'BAC', 'LUV', 'SNY.O',
             'AMD.O', 'NTDOY.PK', 'SNE', 'MSFT.O', 'F', '0593q.L', 'PEP.O', 'NSRGY.PK', 'PG', 'RHHBY.PK', 'PFE', 'MAR.O', 'MGM', 'CHK', 'CVX', 'BA', 'LUV', 'ROKU.O', 'M', 'PYPL.O', 'AMC',
             'ABBV.N', 'ASML.O', 'CGNX.O', 'EA.O', 'EOG.N', 'GILD.O', 'HUM.N', 'JD.O', 'MDB.O', 'ROP.N', 'MSFT.O', 'AMZN.O', 'DIS', 'ZM.O', 'NVDA.O', 'VZ', 'LUV', 'VRTX.O',
             'TTD.O', 'GMED.K', 'APPN.O', 'NOW', 'MTCH.O', 'RUBI.K', 'PENN.O', 'SPLK.O', 'NVDA.O', 'LVGO.O',  'MSFT.O', 'AAPL.O', 'AMZN.O', 'T', 'JPM', 'UNH', 'ATVI.O', 'V', 'LUV',
             'TSLA.O', 'CVX', 'TGT', 'ALGN.O', 'MAR.O', 'AMZN.O', 'AMZN.O', 'EXPE.O', 'LUV', 'TJX', 'V', 'IPG', 'CCL', 'MITT.K', 'MRNA.O', 'DVAX.O',
             'AMZN.O', 'AVGO.O', 'PYPL.O', 'ILMN.O', 'EQIX.O', 'AAPL.O', 'TSM', 'ATVI.O', 'TSLA.O', 'DHR', 'AAPL.O', 'ABBV.N', 'AMZN.O', 'AXP', 'CHWY.K', 'FIVN.O','MRK', 'OKTA.O',
             'TDOC.K', 'VRSN.O', 'LUV', 'NCLH.K', 'AMZN.O', 'MGM', 'EQIX.O', 'F', 'THRM.O', 'BA', 'LVS', 'DIS', 'MDT', 'MRK', 'MAR.O', 'PENN.O', 'DDOG.O', 'AMZN.O', 'TWLO.K', 'NVCR.O', 'ZS.O',
             'TTD.O', 'SHOP.K','TEAM.O', 'MELI.O', 'NVDA.O', 'AMZN.O', 'PYPL.O', 'VLO', 'GOOG.O', 'AAPL.O', 'JPM', 'NFLX.O', 'DLR', 'MSFT.O', 'NVDA.O', 'AMZN.O', 'PYPL.O', 'VLO', 'GOOG.O',
             'AAPL.O', 'JPM', 'NFLX.O', 'DLR', 'MSFT.O','LVGO.O', 'NVDA.O', 'AAPL.O', 'AMZN.O', 'COST.O', 'ZM.O', 'SHOP.K', 'NK.O', 'DPZ', 'W', 'AMZN.O', 'NFLX.O', 'MSFT.O', 'NVDA.O', 'JNJ', 'DIS',
             'LUV', 'TTD.O', 'PANW.K', 'BABA.K']
    
    
    
    
    
    stocks = []
    for p in picks:
        if p not in stocks:
            stocks.append(p)
        
    start = ek.get_data(stocks, fields='TR.CLOSEPRICE', parameters={'SDate': '2020-05-29'})[0]
    start = start.rename(columns = {'Instrument': 'Stocks'})
    start = start.set_index('Stocks')
    
    bm_ticks = ['IVV','IWF','IJH','IJR','IWM','IWD','IVW','ITOT.K','IWB','IWR','IVE','IWP','DGRO.K','IWS','IWV','IUSG.O','IWO','IWN', 
                'OEF', 'IJK', 'IUSV.O', 'HDV', 'IJS','IJJ', 'IJT.O', 'IWY', 'JKE', 'JKH', 'JKD', 'IWC', 'JKG', 'IWL', 'IWX', 'JKF',
                'JKI.O', 'JKL', 'JKK', 'JKJ', 'QQQ.O']
    bm_rets = ek.get_timeseries(bm_ticks, start_date='2019-05-31', end_date='2020-05-29', interval='weekly', fields='CLOSE')
    
    stock_ts_1 = ek.get_timeseries(stocks[0:50], start_date='2019-05-31', end_date='2020-05-29', interval='weekly', fields='CLOSE')
    stock_ts_2 = ek.get_timeseries(stocks[50:100], start_date='2019-05-31', end_date='2020-05-29', interval='weekly', fields='CLOSE')
    stock_ts_3 = ek.get_timeseries(stocks[100:], start_date='2019-05-31', end_date='2020-05-29', interval='weekly', fields='CLOSE')
    
    stock_ts = stock_ts_1.join(stock_ts_2 )
    stock_ts = stock_ts.join(stock_ts_3 )
    
    etfs = bm_ticks
    fields = [ek.TR_Field('TR.FundName'), ek.TR_Field('TR.CLOSEPRICE', params={'SDate': '2020-05-29'})]
    bms_1 = ek.get_data(etfs, fields=fields)[0]
    
    start.to_pickle('start.pkl')
    bm_rets.to_pickle('bm_rets.pkl')
    stock_ts.to_pickle('Stocks_setup.pkl')
    bms_1.to_pickle('Benchmarks.pkl')

In [ ]:
lp_setup()

In [3]:
def league():
    ken = pd.DataFrame({'Stocks': ['LUV', 'UBER.K', 'NVDA.O', 'MCD', 'FB.O', 'RF', 'TJX', 'Z.O', 'NVS', 'GILD.O'], 'Investment': [10000, 20000, 5000, 5000, 10000, 15000, 5000, 10000,10000, 10000], 'id': 'Ken'})
    ann_mar = pd.DataFrame({'Stocks': ['SYK', 'AEG', 'LMT', 'TOT', 'AMZN.O', 'GOOGL.O'], 'Investment': [10000,25000,20000,25000,10000,10000], 'id': 'Ann Marie'})
    hoser = pd.DataFrame({'Stocks': ['BE', 'NVDA.O','ADI.O', 'PLUG.O', 'MXIM.O', 'DAL', 'LUV', 'CRWD.O', 'SGEN.O', 'NOW'], 'Investment': [8750,8750,8750,8750,8750,15000,15000,8750,8750,8750], 'id': 'Hosegood'})
    jack = pd.DataFrame({'Stocks': [ 'TXT', 'BORR.K', 'FB.O', 'QCOM.O', 'NVDA.O', 'PYPL.O', 'CSCO.O', 'WIX.O', 'APTV.K', 'LUV'], 'Investment': [5000,5000,15000,10000,15000,10000,10000,15000,5000,10000], 'id': 'Jack'})
    christi = pd.DataFrame({'Stocks': [ 'LUV', 'TMO', 'PING.K', 'PAA', 'AZN.P', 'GILD.O', 'WYNN.O', 'QCOM.O', 'ZM.O'], 'Investment': [10000, 17000, 8500, 9750, 14750, 13000, 10000, 8000, 9000], 'id': 'Jeff Christi'})
    flam = pd.DataFrame({'Stocks': ['AAPL.O', 'NFLX.O', 'BA', 'BLMN.O', 'FEYE.O', 'KSU', 'JPM', 'MSFT.O', 'WYNN.O', 'FB.O',], 'Investment': [20000,5000,5000,5000,20000,10000,10000,10000,10000,5000], 'id': 'Louis'})
    ak = pd.DataFrame({'Stocks': ['GOOGL.O', 'AMZN.O', 'AAPL.O', 'BX', 'FB.O', 'HD', 'MSFT.O', 'NFLX.O', 'NKE', 'UNH'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id': 'Anthony'})
    sd = pd.DataFrame({'Stocks': ['CHWY.K', 'AMD.O', 'PYPL.O', 'MELI.O', 'SPLK.O', 'CRSP.O', 'TWLO.K', 'BL.O','SWKS.O', 'NTLA.O',], 'Investment': [8000, 12000, 10000, 8000, 12000, 8000, 10000, 10000, 10000, 12000], 'id':'Sergio'})
    db = pd.DataFrame({'Stocks': ['MSFT.O', 'AMZN.O', 'TSLA.O', 'AAPL.O', 'XOM', 'JNJ', 'AXP', 'CLX', 'BRKb', 'CVS'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Debbie'})
    mk = pd.DataFrame({'Stocks': ['AMZN.O', 'MSFT.O', 'TSLA.O', 'AMD.O', 'BA', 'LUV', 'CCL','MGM', 'LYV', 'DKNG.O',], 'Investment': [9769, 7330, 12525, 10444, 10210, 10433, 10215, 10291, 8849, 9925], 'id': 'Mike'})
    ab = pd.DataFrame({'Stocks': ['MSFT.O', 'AMZN.O', 'NFLX.O', 'PYPL.O', 'UNH', 'HD', 'DIS', 'CLX', 'INO.O', 'NVDA.O'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Ali'})
    jw = pd.DataFrame({'Stocks': ['ZBRA.O', 'FLIR.O', 'ECL', 'C', 'BAC', 'LUV', 'SNY.O'], 'Investment': [17500, 17500, 17500, 10000, 10000, 17500, 10000], 'id': 'Westy'})
    jpl = pd.DataFrame({'Stocks': ['AMD.O', 'NTDOY.PK', 'SNE', 'MSFT.O', 'F', '0593q.L', 'PEP.O', 'NSRGY.PK', 'PG', 'RHHBY.PK', 'PFE'] ,'Investment': [5000, 5000, 5000, 5000, 5000, 5000, 10000, 15000, 15000, 15000, 15000], 'id': 'JPL'})
    aw = pd.DataFrame({'Stocks': ['MAR.O', 'MGM', 'CHK', 'CVX', 'BA', 'LUV', 'ROKU.O', 'M', 'PYPL.O', 'AMC'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Alyssa'})
    pr = pd.DataFrame({'Stocks': [ 'ABBV.N', 'ASML.O', 'CGNX.O', 'EA.O', 'EOG.N', 'GILD.O', 'HUM.N', 'JD.O', 'MDB.O', 'ROP.N'], 'Investment': [15000,18000,3000,5000,4000,14000,10000,11000,15000,5000], 'id':'Paul R'})
    fr = pd.DataFrame({'Stocks': ['AAPL.O', 'ABBV.N', 'AMZN.O', 'AXP', 'CHWY.K', 'FIVN.O','MRK', 'OKTA.O','TDOC.K', 'VRSN.O'], 'Investment': [17000,8000,21000,6000,10000,10000,6000,11000,8000,3000], 'id':'Farrah'})
    el = pd.DataFrame({'Stocks': [ 'MSFT.O', 'AMZN.O', 'DIS', 'ZM.O', 'NVDA.O', 'VZ', 'LUV', 'VRTX.O'], 'Investment': [20000, 15000, 10000, 10000, 10000, 15000, 10000, 10000], 'id':'Evan'})
    jb = pd.DataFrame({'Stocks': [ 'TTD.O', 'GMED.K', 'APPN.O', 'NOW', 'MTCH.O', 'RUBI.K', 'PENN.O', 'SPLK.O', 'NVDA.O', 'LVGO.O'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'JB'})
    ds = pd.DataFrame({'Stocks': [ 'MSFT.O', 'AAPL.O', 'AMZN.O', 'T', 'JPM', 'UNH', 'ATVI.O', 'V', 'LUV'], 'Investment': [14843.25, 14943.18, 14654.22, 15183.12, 9925.62, 9755.20, 10581.06, 4881, 5232.30], 'id':'Daniel'})
    eh = pd.DataFrame({'Stocks': [ 'TSLA.O', 'CVX', 'TGT', 'ALGN.O', 'MAR.O', 'AMZN.O'], 'Investment': [17535, 5502, 7339.8, 14737.2, 5310, 48847.4], 'id':'Emily'})
    jt = pd.DataFrame({'Stocks': [ 'AMZN.O', 'EXPE.O', 'LUV', 'TJX', 'V', 'IPG', 'CCL', 'MITT.K', 'MRNA.O', 'DVAX.O'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Jon T'})
    ar = pd.DataFrame({'Stocks': [ 'AMZN.O', 'AVGO.O', 'PYPL.O', 'ILMN.O', 'EQIX.O', 'AAPL.O', 'TSM', 'ATVI.O', 'TSLA.O', 'DHR'], 'Investment': [10500, 10500, 10500, 10500, 10500, 10500, 10500, 10500, 5500, 10500], 'id':'Anish'})
    mb = pd.DataFrame({'Stocks': ['ASML.O', 'MSFT.O'], 'Investment': [9990, 10], 'id':'Burke'})
    nd = pd.DataFrame({'Stocks': ['LUV', 'NCLH.K', 'AMZN.O', 'MGM', 'EQIX.O'], 'Investment': [20000, 20000, 20000, 20000, 20000], 'id':'Dado'})
    gk = pd.DataFrame({'Stocks': ['F', 'THRM.O', 'BA', 'LVS', 'DIS', 'MDT', 'MRK', 'MAR.O'], 'Investment': [12500, 12500, 12500, 12500, 12500, 12500, 12500, 12500], 'id':'Greg'})
    cp = pd.DataFrame({'Stocks': ['PENN.O', 'DDOG.O', 'AMZN.O', 'TWLO.K', 'NVCR.O', 'ZS.O', 'TTD.O', 'SHOP.K','TEAM.O', 'MELI.O'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Chris P'})
    ph = pd.DataFrame({'Stocks': ['NVDA.O', 'AMZN.O', 'PYPL.O', 'VLO', 'GOOG.O', 'AAPL.O', 'JPM', 'NFLX.O', 'DLR', 'MSFT.O'], 'Investment': [15000, 15000, 15000, 10000, 10000, 10000, 10000, 5000, 5000, 5000], 'id':'Paul H'})
    hh = pd.DataFrame({'Stocks': ['AMZN.O', 'NFLX.O', 'MSFT.O', 'NVDA.O', 'JNJ', 'DIS', 'LUV', 'TTD.O', 'PANW.K', 'BABA.K'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Henry'})
    sb = pd.DataFrame({'Stocks': ['LVGO.O', 'NVDA.O', 'AAPL.O', 'AMZN.O', 'COST.O', 'ZM.O', 'SHOP.K', 'NK.O', 'DPZ', 'W'], 'Investment': [5000, 10000, 15000, 15000, 12500, 5000, 7500, 5000, 12500, 12500], 'id':'Scott B'})
    
    players = [ken, ann_mar, hoser, jack, christi, flam, ak, sd, db, mk, ab, jw, jpl, aw, pr, fr, el, jb, ds, eh, jt, ar, mb, nd, gk, cp, ph, hh, sb]
    master = pd.concat(players)
    master = master.set_index('Stocks')
    start = pd.read_pickle('start.pkl')
    
    today = datetime.date.today()
    last_date = today.strftime('%Y-%m-%d')
    
    stocks = start.index.to_list()
    fields = [ek.TR_Field('DSPLY_NAME'), ek.TR_Field('TR.GICSSector'), ek.TR_Field('TR.CLOSEPRICE', params={'SDate': last_date})]
    today = ek.get_data(stocks, fields=fields)[0]
    today = today.rename(columns = {'Instrument': 'Stocks'})
    today = today.set_index('Stocks')

    master = master.join(start)
    master['Shares'] = master['Investment'] / master['Close Price']
    master = master.rename(columns = {'Close Price': 'Cost per Share'})
    master = master.join(today)
    master['Todays Value'] = master['Shares'] * master['Close Price']
    roster = master['id'].drop_duplicates().to_list()

    
    bms = []
    bm_rets = pd.read_pickle('bm_rets.pkl').pct_change().dropna()
    
    for r in roster:
        p = master[master['id']==r]
        x = p.index.to_list()
        t = np.array(p['Shares'])
        s = pd.read_pickle('Stocks_setup.pkl').filter(x)
        s = s.dropna()
        s['Strat'] = np.dot(t, s.T)
        w = s.pct_change().dropna()
        l = bm_rets.join(w['Strat'])
        lv = l.corr()
        bm = lv['Strat'][0:-1].idxmax()
        r_2 = round(lv['Strat'][0:-1].max()**2, 4)*100
        q = (r , bm, r_2)
        bms.append(q)
    

    benchmarks = pd.DataFrame(bms)
    benchmarks = benchmarks.rename(columns = {0:'id', 1:'Benchmark', 2:'R Squared'})
    benchmarks = benchmarks.set_index('id')
    master = master.reset_index()
    master = master.set_index('id')
    master = master.join(benchmarks)
    master = master.reset_index()
    league = master.groupby('id').sum()
    league = league.filter(['Investment', 'Todays Value'])
    league['Total Return'] = ((league['Todays Value'])/league['Investment'])-1
    tr_tab = league['Total Return'].quantile([0.25, 0.5, 0.75])
    trs = league['Total Return'].to_list()

    quants = []
    for t in trs:
        if t > tr_tab.iloc[2]:
            x = emoji.emojize(':heavy_dollar_sign::heavy_dollar_sign::heavy_dollar_sign::heavy_dollar_sign:')
        elif t <= tr_tab.iloc[2] and t > tr_tab.iloc[1]:
            x = emoji.emojize(':heavy_dollar_sign::heavy_dollar_sign::heavy_dollar_sign:')
        elif t <= tr_tab.iloc[1] and t > tr_tab.iloc[0]:
             x = emoji.emojize(':heavy_dollar_sign::heavy_dollar_sign:')
        else:
            x = emoji.emojize(':poop::poop::poop::poop:', use_aliases=True)
        quants.append(x)
    
    league['Rank'] = quants
    
    league = league.sort_values(by = 'Total Return', ascending = False)
    master = master.set_index('id')
    league_fin = league.join(master['Benchmark'])
    league_fin = league_fin.drop_duplicates()
    league_fin = league_fin.sort_values('Total Return', ascending=False)
    etfs = ['IVV','IWF','IJH','IJR','IWM','IWD','IVW','ITOT.K','IWB','IWR','IVE','IWP','DGRO.K','IWS','IWV','IUSG.O','IWO','IWN', 
                'OEF', 'IJK', 'IUSV.O', 'HDV', 'IJS','IJJ', 'IJT.O', 'IWY', 'JKE', 'JKH', 'JKD', 'IWC', 'JKG', 'IWL', 'IWX', 'JKF',
                'JKI.O', 'JKL', 'JKK', 'JKJ', 'QQQ.O']
    fields = [ek.TR_Field('TR.FundName'), ek.TR_Field('TR.CLOSEPRICE', params={'SDate': last_date})]
    bms_2 = ek.get_data(etfs, fields=fields)[0]
    bms_2 = bms_2.rename(columns = {'Instrument':'Benchmark'})
    bms_2 = bms_2.set_index('Benchmark')
    bms_1 = pd.read_pickle('Benchmarks.pkl')
    bmarks = bms_1.rename(columns = {'Instrument':'Benchmark', 'Fund Name': 'Benchmark Name', 'Close Price': 'Cost'}).set_index('Benchmark')
    bmarks = bmarks.join(bms_2)
    bmarks['Benchmark Total Return'] = ((bmarks['Close Price'].astype(float))/bmarks['Cost'].astype(float))-1
    b_marks = league_fin['Benchmark'].to_list()

    bmtr = []
    bmname = []
    for b in b_marks:
        x = bmarks['Benchmark Total Return'].loc[b]
        y = bmarks['Benchmark Name'].loc[b]
        bmtr.append(x)
        bmname.append(y)
    
    league_fin['Benchmark Name'] = bmname
    league_fin['Beanchmark Total Return'] = bmtr
    league_fin['Outperformance'] = league_fin['Total Return'] - league_fin['Beanchmark Total Return']
    league_fin['Outperforming Benchmark'] =[emoji.emojize(':heavy_check_mark:', use_aliases=True) if x > 0 else emoji.emojize(':x:', use_aliases=True) for x in league_fin['Outperformance']]
    league_final = league_fin.drop(['Benchmark', 'Outperformance'], axis = 1)
    master.to_pickle('master.pkl')

    
    
    
    return  league_final

In [5]:
x = league()
x

C:\Users\jgarden\AppData\Local\Continuum\miniconda3\lib\site-packages\eikon\data_grid.py:247: FutureWarning:

The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

C:\Users\jgarden\AppData\Local\Continuum\miniconda3\lib\site-packages\eikon\data_grid.py:247: FutureWarning:

The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

,Investment,Todays Value,Total Return,Rank,Benchmark Name,Beanchmark Total Return,Outperforming Benchmark
id,,,,,,,
Jon T,100000.00,122910.361744,0.229104,💲💲💲💲,iShares Russell Mid-Cap Value ETF,0.065360,✔
Alyssa,100000.00,118065.784926,0.180658,💲💲💲💲,iShares Russell 2000 Value ETF,0.071961,✔
Mike,99991.00,116172.113883,0.161826,💲💲💲💲,iShares Russell Mid-Cap ETF,0.049905,✔
Dado,100000.00,115008.860862,0.150089,💲💲💲💲,iShares Morningstar Small-Cap ETF,0.057733,✔
Hosegood,100000.00,114453.922463,0.144539,💲💲💲💲,iShares Core S&P Total US Stock Market ETF,0.050770,✔
Jack,100000.00,112007.634814,0.120076,💲💲💲💲,iShares Core S&P Small-Cap ETF,0.073934,✔
Greg,100000.00,111592.617790,0.115926,💲💲💲💲,iShares Russell Mid-Cap Value ETF,0.065360,✔
Emily,99271.40,109740.650000,0.105461,💲💲💲,Invesco QQQ Trust Series 1,0.055108,✔
Louis,100000.00,110045.584454,0.100456,💲💲💲,iShares Russell Mid-Cap ETF,0.049905,✔
Ann Marie,100000.00,109551.529311,0.095515,💲💲💲,iShares Morningstar Small-Cap ETF,0.057733,✔
Jeff Christi,100000.00,108538.722354,0.085387,💲💲💲,Invesco QQQ Trust Series 1,0.055108,✔
Debbie,100000.00,107863.196188,0.078632,💲💲💲,iShares S&P 100 ETF,0.050751,✔
Evan,100000.00,107298.974436,0.072990,💲💲💲,Invesco QQQ Trust Series 1,0.055108,✔
Henry,100000.00,106912.057200,0.069121,💲💲💲,Invesco QQQ Trust Series 1,0.055108,✔
Westy,100000.00,106757.807321,0.067578,💲💲,iShares S&P Mid-Cap 400 Value ETF,0.070715,❌
Daniel,99998.95,106744.580000,0.067457,💲💲,iShares S&P 100 ETF,0.050751,✔
Anish,100000.00,106485.405071,0.064854,💲💲,Invesco QQQ Trust Series 1,0.055108,✔
Sergio,100000.00,106359.119821,0.063591,💲💲,iShares Morningstar Small-Cap Growth ETF,0.029132,✔
Burke,10000.00,10558.891287,0.055889,💲💲,iShares Core S&P Total US Stock Market ETF,0.050770,✔
Paul H,100000.00,105543.501214,0.055435,💲💲,Invesco QQQ Trust Series 1,0.055108,✔
Scott B,100000.00,105365.036970,0.053650,💲💲,Invesco QQQ Trust Series 1,0.055108,❌
Farrah,100000.00,104845.544768,0.048455,💩💩💩💩,Invesco QQQ Trust Series 1,0.055108,❌
Anthony,100000.00,104661.515198,0.046615,💩💩💩💩,iShares Russell Top 200 Growth Index Fund,0.052368,❌
JB,100000.00,104485.651775,0.044857,💩💩💩💩,iShares Morningstar Small-Cap Growth ETF,0.029132,✔
Chris P,100000.00,104283.318212,0.042833,💩💩💩💩,iShares Morningstar Mid-Cap Growth ETF,0.027681,✔
Ken,100000.00,104026.064188,0.040261,💩💩💩💩,iShares Russell 2000 ETF,0.052412,❌
JPL,100000.00,103459.986732,0.034600,💩💩💩💩,iShares Russell Top 200 Growth Index Fund,0.052368,❌
Ali,100000.00,102616.986983,0.026170,💩💩💩💩,Invesco QQQ Trust Series 1,0.055108,❌
Paul R,100000.00,101490.366379,0.014904,💩💩💩💩,Invesco QQQ Trust Series 1,0.055108,❌

In [6]:
def table(x):
    df_6 = x.reset_index()
    width = [50, 50, 50, 50, 70, 120, 50, 50]

    rowEvenColor = 'lightgrey'
    rowOddColor = 'white'
    fig_6 = go.Figure(data=[go.Table(
        columnwidth=width,
        header = dict(values = list(df_6.columns),
                      fill_color = '#003C5A',
                      font = dict(family= 'pt sans narrow', size = 20),
                      font_color = 'white',
                      align = 'center'),
        cells = dict(values=[df_6['id'],df_6['Investment'], df_6['Todays Value'], df_6['Total Return'], df_6['Rank'], df_6['Benchmark Name'],
                             df_6['Beanchmark Total Return'], df_6['Outperforming Benchmark']],
                     fill_color = [[rowOddColor, rowEvenColor]*50],
                     font = dict(family= 'pt sans narrow', size = 18),
                     height = 30,
                     format = [[None], ['$,.2f'], ['$,.2f'],['.2%'],[None],[None],['.2%'],[None]],
                     align = ['left']))
                           ])

    fig_6.update_layout(
        margin=dict(l=20, r=20, t=30, b=20),
        height = 1400,
        width = 1245,
        title="Liar'$ Poker")

    #py.iplot(fig_6, filename='fig_6')
    pio.write_html(fig_6, file='Liars.html', auto_open=True)

In [7]:
table(x)

In [8]:
s = pd.read_pickle('master.pkl')

In [9]:
names = s.index.drop_duplicates().to_list()

for n in names:
    df = s[s.index == n]
    df = df.filter(['Stocks', 'Investment', 'Cost per Share', 'Shares', 'DSPLY_NAME', 'GICS Sector Name', 'Close Price', 'Todays Value'])
    df['Return'] = (df['Close Price']/df['Cost per Share'])-1
    
    df_tots = pd.DataFrame({'Name': n, 'Total Invested':df['Investment'].sum(), "Today's Value": df['Todays Value'].sum(), 'Total Dividends': 0}, index = [0])
    df_tots['Total Return'] =  ((df_tots["Today's Value"] + df_tots['Total Dividends'])/df_tots['Total Invested'])-1
    
    fig = make_subplots(
        rows = 2, cols = 1,
        vertical_spacing=0.02,
        row_heights = [0.75, 0.25],
        specs=[[{"type": "table"}],
               [{"type": "table"}]])
    
    
    width = [50, 50, 50, 50, 100, 120, 50, 50]   
                                                                                               
    rowEvenColor = 'lightgrey'
    rowOddColor = 'white'
    fig.append_trace(go.Table(
        columnwidth=width,
        header = dict(values = list(df.columns),
                      fill_color = '#003C5A',
                      font = dict(family= 'pt sans narrow', size = 20),
                      font_color = 'white',
                      align = 'center'),
        cells = dict(values=[df['Stocks'],df['Investment'], df['Cost per Share'], df['Shares'],df['DSPLY_NAME'], df['GICS Sector Name'], df['Close Price'],df['Todays Value'],
                             df['Return']],
                     fill_color = [[rowOddColor, rowEvenColor]*50],
                     font = dict(family= 'pt sans narrow', size = 18),
                     height = 30,
                     format = [[None], ['$,.2f'], ['$,.2f'],['.2f'],[None],[None],['$,.2f'],['$,.2f'],['.2%']],
                     align = ['left'])), row=1, col = 1)

                                                                                               
    fig.append_trace(go.Table(go.Table(
        columnwidth=width,
        header = dict(values = list(df_tots.columns),
                      fill_color = '#003C5A',
                      font = dict(family= 'pt sans narrow', size = 20),
                      font_color = 'white',
                      align = 'center'),
        cells = dict(values=[df_tots['Name'],df_tots['Total Invested'], df_tots["Today's Value"], df_tots['Total Dividends'],df_tots['Total Return']],
                     fill_color = [[rowOddColor, rowEvenColor]*50],
                     font = dict(family= 'pt sans narrow', size = 18),
                     height = 30,
                     format = [[None], ['$,.2f'], ['$,.2f'],['$,.2f'],['.2%']],
                     align = ['left']))),row=2, col = 1)
    fig.update_layout(
        margin=dict(l=10, r=10, t=40, b=10),
        height = 562,
        width = 1000,
        title="{} Portfolio".format(n))                                                                                            
                                                                                             
    #py.iplot(fig_6, filename='fig_6')
    pio.write_html(fig, file='{}_liars.html'.format(n), auto_open=True)

In [10]:
'Name': n, 'Total Invested':df['Investment'].sum(), "Today's Value": df['Todays Value'].sum(), 'Total Dividends': 0}

SyntaxError: invalid syntax (<ipython-input-10-92df526ffef1>, line 1)

In [13]:
def league_2():
    ken = pd.DataFrame({'Stocks': ['LUV', 'UBER.K', 'NVDA.O', 'MCD', 'FB.O', 'RF', 'TJX', 'Z.O', 'NVS', 'GILD.O'], 'Investment': [10000, 20000, 5000, 5000, 10000, 15000, 5000, 10000,10000, 10000], 'id': 'Ken'})
    ann_mar = pd.DataFrame({'Stocks': ['SYK', 'AEG', 'LMT', 'TOT', 'AMZN.O', 'GOOGL.O'], 'Investment': [10000,25000,20000,25000,10000,10000], 'id': 'Ann Marie'})
    hoser = pd.DataFrame({'Stocks': ['BE', 'NVDA.O','ADI.O', 'PLUG.O', 'MXIM.O', 'DAL', 'LUV', 'CRWD.O', 'SGEN.O', 'NOW'], 'Investment': [8750,8750,8750,8750,8750,15000,15000,8750,8750,8750], 'id': 'Hosegood'})
    jack = pd.DataFrame({'Stocks': [ 'TXT', 'BORR.K', 'FB.O', 'QCOM.O', 'NVDA.O', 'PYPL.O', 'CSCO.O', 'WIX.O', 'APTV.K', 'LUV'], 'Investment': [5000,5000,15000,10000,15000,10000,10000,15000,5000,10000], 'id': 'Jack'})
    christi = pd.DataFrame({'Stocks': [ 'LUV', 'TMO', 'PING.K', 'PAA', 'AZN.P', 'GILD.O', 'WYNN.O', 'QCOM.O', 'ZM.O'], 'Investment': [10000, 17000, 8500, 9750, 14750, 13000, 10000, 8000, 9000], 'id': 'Jeff Christi'})
    flam = pd.DataFrame({'Stocks': ['AAPL.O', 'NFLX.O', 'BA', 'BLMN.O', 'FEYE.O', 'KSU', 'JPM', 'MSFT.O', 'WYNN.O', 'FB.O',], 'Investment': [20000,5000,5000,5000,20000,10000,10000,10000,10000,5000], 'id': 'Louis'})
    ak = pd.DataFrame({'Stocks': ['GOOGL.O', 'AMZN.O', 'AAPL.O', 'BX', 'FB.O', 'HD', 'MSFT.O', 'NFLX.O', 'NKE', 'UNH'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id': 'Anthony'})
    sd = pd.DataFrame({'Stocks': ['CHWY.K', 'AMD.O', 'PYPL.O', 'MELI.O', 'SPLK.O', 'CRSP.O', 'TWLO.K', 'BL.O','SWKS.O', 'NTLA.O',], 'Investment': [8000, 12000, 10000, 8000, 12000, 8000, 10000, 10000, 10000, 12000], 'id':'Sergio'})
    db = pd.DataFrame({'Stocks': ['MSFT.O', 'AMZN.O', 'TSLA.O', 'AAPL.O', 'XOM', 'JNJ', 'AXP', 'CLX', 'BRKb', 'CVS'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Debbie'})
    mk = pd.DataFrame({'Stocks': ['AMZN.O', 'MSFT.O', 'TSLA.O', 'AMD.O', 'BA', 'LUV', 'CCL','MGM', 'LYV', 'DKNG.O',], 'Investment': [9769, 7330, 12525, 10444, 10210, 10433, 10215, 10291, 8849, 9925], 'id': 'Mike'})
    ab = pd.DataFrame({'Stocks': ['MSFT.O', 'AMZN.O', 'NFLX.O', 'PYPL.O', 'UNH', 'HD', 'DIS', 'CLX', 'INO.O', 'NVDA.O'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Ali'})
    jw = pd.DataFrame({'Stocks': ['ZBRA.O', 'FLIR.O', 'ECL', 'C', 'BAC', 'LUV', 'SNY.O'], 'Investment': [17500, 17500, 17500, 10000, 10000, 17500, 10000], 'id': 'Westy'})
    jpl = pd.DataFrame({'Stocks': ['AMD.O', 'NTDOY.PK', 'SNE', 'MSFT.O', 'F', '0593q.L', 'PEP.O', 'NSRGY.PK', 'PG', 'RHHBY.PK', 'PFE'] ,'Investment': [5000, 5000, 5000, 5000, 5000, 5000, 10000, 15000, 15000, 15000, 15000], 'id': 'JPL'})
    aw = pd.DataFrame({'Stocks': ['MAR.O', 'MGM', 'CHK', 'CVX', 'BA', 'LUV', 'ROKU.O', 'M', 'PYPL.O', 'AMC'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Alyssa'})
    pr = pd.DataFrame({'Stocks': [ 'ABBV.N', 'ASML.O', 'CGNX.O', 'EA.O', 'EOG.N', 'GILD.O', 'HUM.N', 'JD.O', 'MDB.O', 'ROP.N'], 'Investment': [15000,18000,3000,5000,4000,14000,10000,11000,15000,5000], 'id':'Paul R'})
    fr = pd.DataFrame({'Stocks': ['AAPL.O', 'ABBV.N', 'AMZN.O', 'AXP', 'CHWY.K', 'FIVN.O','MRK', 'OKTA.O','TDOC.K', 'VRSN.O'], 'Investment': [17000,8000,21000,6000,10000,10000,6000,11000,8000,3000], 'id':'Farrah'})
    el = pd.DataFrame({'Stocks': [ 'MSFT.O', 'AMZN.O', 'DIS', 'ZM.O', 'NVDA.O', 'VZ', 'LUV', 'VRTX.O'], 'Investment': [20000, 15000, 10000, 10000, 10000, 15000, 10000, 10000], 'id':'Evan'})
    jb = pd.DataFrame({'Stocks': [ 'TTD.O', 'GMED.K', 'APPN.O', 'NOW', 'MTCH.O', 'RUBI.K', 'PENN.O', 'SPLK.O', 'NVDA.O', 'LVGO.O'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'JB'})
    ds = pd.DataFrame({'Stocks': [ 'MSFT.O', 'AAPL.O', 'AMZN.O', 'T', 'JPM', 'UNH', 'ATVI.O', 'V', 'LUV'], 'Investment': [14843.25, 14943.18, 14654.22, 15183.12, 9925.62, 9755.20, 10581.06, 4881, 5232.30], 'id':'Daniel'})
    eh = pd.DataFrame({'Stocks': [ 'TSLA.O', 'CVX', 'TGT', 'ALGN.O', 'MAR.O', 'AMZN.O'], 'Investment': [17535, 5502, 7339.8, 14737.2, 5310, 48847.4], 'id':'Emily'})
    jt = pd.DataFrame({'Stocks': [ 'AMZN.O', 'EXPE.O', 'LUV', 'TJX', 'V', 'IPG', 'CCL', 'MITT.K', 'MRNA.O', 'DVAX.O'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Jon T'})
    ar = pd.DataFrame({'Stocks': [ 'AMZN.O', 'AVGO.O', 'PYPL.O', 'ILMN.O', 'EQIX.O', 'AAPL.O', 'TSM', 'ATVI.O', 'TSLA.O', 'DHR'], 'Investment': [10500, 10500, 10500, 10500, 10500, 10500, 10500, 10500, 5500, 10500], 'id':'Anish'})
    mb = pd.DataFrame({'Stocks': ['ASML.O', 'MSFT.O'], 'Investment': [9990, 10], 'id':'Burke'})
    nd = pd.DataFrame({'Stocks': ['LUV', 'NCLH.K', 'AMZN.O', 'MGM', 'EQIX.O'], 'Investment': [20000, 20000, 20000, 20000, 20000], 'id':'Dado'})
    gk = pd.DataFrame({'Stocks': ['F', 'THRM.O', 'BA', 'LVS', 'DIS', 'MDT', 'MRK', 'MAR.O'], 'Investment': [12500, 12500, 12500, 12500, 12500, 12500, 12500, 12500], 'id':'Greg'})
    cp = pd.DataFrame({'Stocks': ['PENN.O', 'DDOG.O', 'AMZN.O', 'TWLO.K', 'NVCR.O', 'ZS.O', 'TTD.O', 'SHOP.K','TEAM.O', 'MELI.O'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Chris P'})
    ph = pd.DataFrame({'Stocks': ['NVDA.O', 'AMZN.O', 'PYPL.O', 'VLO', 'GOOG.O', 'AAPL.O', 'JPM', 'NFLX.O', 'DLR', 'MSFT.O'], 'Investment': [15000, 15000, 15000, 10000, 10000, 10000, 10000, 5000, 5000, 5000], 'id':'Paul H'})
    hh = pd.DataFrame({'Stocks': ['AMZN.O', 'NFLX.O', 'MSFT.O', 'NVDA.O', 'JNJ', 'DIS', 'LUV', 'TTD.O', 'PANW.K', 'BABA.K'], 'Investment': [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], 'id':'Henry'})
    sb = pd.DataFrame({'Stocks': ['LVGO.O', 'NVDA.O', 'AAPL.O', 'AMZN.O', 'COST.O', 'ZM.O', 'SHOP.K', 'NK.O', 'DPZ', 'W'], 'Investment': [5000, 10000, 15000, 15000, 12500, 5000, 7500, 5000, 12500, 12500], 'id':'Scott B'})
    
    players = [ken, ann_mar, hoser, jack, christi, flam, ak, sd, db, mk, ab, jw, jpl, aw, pr, fr, el, jb, ds, eh, jt, ar, mb, nd, gk, cp, ph, hh, sb]
    master = pd.concat(players)
    master = master.set_index('Stocks')
    start = pd.read_pickle('start.pkl')
    
    today = datetime.date.today()
    last_date = today.strftime('%Y-%m-%d')
    
    stocks = start.index.to_list()
    fields = [ek.TR_Field('DSPLY_NAME'), ek.TR_Field('TR.GICSSector'), ek.TR_Field('TR.CLOSEPRICE', params={'SDate': last_date}),
             ek.TR_Field('TR.TotalReturn', params=dict('SDate'='2020-05-31','EDate'= last_date)), ]
    today = ek.get_data(stocks, fields=fields)[0]
    today = today.rename(columns = {'Instrument': 'Stocks'})
    today = today.set_index('Stocks')
    
    
    
    return start

In [14]:
league_2()

        Close Price
Stocks
LUV           32.10
UBER.K        36.32
NVDA.O       355.02
MCD          186.32
FB.O         225.09
...             ...
NK.O           6.74
DPZ          385.84
W            171.55
PANW.K       235.27
BABA.K       207.39

[148 rows x 1 columns]